const DATE_WITHOUT_ = 'YYYYMMDD';
const DATE_WITH_ = 'DD-MM-YYYY';
const CREATE_DATE = 'MMM D, YYYY';
const FORMATTED_DATE = 'dddd, DD MMMM';
const TIME_FORMAT = 'HH:mm';

export {CREATE_DATE, DATE_WITHOUT_, DATE_WITH_, FORMATTED_DATE, TIME_FORMAT};
